# The rails root relative path to your blog (for loading Jekyll's _config.yml)
development:
  published_path: /Users/yortz/projects/colorsoflife/public/blog
  relative_blog_path: /Users/yortz/projects/colorsoflife/source
  posts_path: _posts
  
test:
  published_path: /Users/yortz/projects/octopress-admin/spec/data/blog/public/blog
  relative_blog_path: /Users/yortz/projects/octopress-admin/spec/data/blog/source
  posts_path: _posts
  
categories:
  - category_1: events
  - category_2: news
  - category_3: photocontest
  
site:
  title: Octopress Admin
  website: http://mydomain.com